"""Cleanup deterministic UI test data generated by iter14_ui_data_setup.py."""

from __future__ import annotations

import asyncio
import json
import os
import uuid
from pathlib import Path

import asyncpg
from dotenv import load_dotenv


ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / "backend" / ".env")

DB_CFG = {
    "user": os.environ["SUPABASE_DB_USER"],
    "password": os.environ["SUPABASE_DB_PASSWORD"],
    "host": os.environ["SUPABASE_DB_HOST"],
    "port": int(os.environ["SUPABASE_DB_PORT"]),
    "database": os.environ["SUPABASE_DB_NAME"],
}

IDS_PATH = ROOT / "test_reports" / "iter14_ui_ids.json"


async def run_cleanup() -> None:
    conn = await asyncpg.connect(**DB_CFG, statement_cache_size=0)
    try:
        ids = {}
        if IDS_PATH.exists():
            ids = json.loads(IDS_PATH.read_text(encoding="utf-8") or "{}")

        order_ids = [x for x in [ids.get("ready_order_id"), ids.get("request_order_id")] if x]
        if order_ids:
            uuids = [uuid.UUID(x) for x in order_ids]
            await conn.execute("delete from work_logs where order_id = any($1::uuid[])", uuids)
            await conn.execute("delete from transactions where order_id = any($1::uuid[])", uuids)
            await conn.execute("delete from order_items where order_id = any($1::uuid[])", uuids)
            await conn.execute("delete from orders where id = any($1::uuid[])", uuids)

        if ids.get("customer_id"):
            await conn.execute("delete from customers where id=$1", uuid.UUID(ids["customer_id"]))

        # defensive cleanup by notes/name pattern
        await conn.execute("delete from work_logs where order_id in (select id from orders where notes like 'TEST_iter14_ui_%')")
        await conn.execute("delete from transactions where order_id in (select id from orders where notes like 'TEST_iter14_ui_%')")
        await conn.execute("delete from order_items where order_id in (select id from orders where notes like 'TEST_iter14_ui_%')")
        await conn.execute("delete from orders where notes like 'TEST_iter14_ui_%'")
        await conn.execute("delete from customers where name like 'TEST_iter14_ui_%'")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(run_cleanup())
    print("CLEANUP_OK")
